### ISSUE TITLE
Use local/dockerized Postgres?

### ISSUE THREAD

**Issue by mrysn** [james-langridge/personal-trainer-planner#81]
How can I use a local or dockerized instance of Postgres instead of Railway?

**Comment by james-langridge** [comment]
You can set the `DATABASE_URL` env var to any Postgres instance you like, eg, `DATABASE_URL=postgresql://<USERNAME>:<PASSWORD>@localhost:5432/<DATABASE_NAME>`.  Let me know if you need more help.
